/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "AddressDiscovery",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AddressDiscovery__factory>;
    getContractFactory(
      name: "CBDCAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CBDCAccessControl__factory>;
    getContractFactory(
      name: "KeyDictionary",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KeyDictionary__factory>;
    getContractFactory(
      name: "RealDigital",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RealDigital__factory>;
    getContractFactory(
      name: "RealDigitalDefaultAccount",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RealDigitalDefaultAccount__factory>;
    getContractFactory(
      name: "RealDigitalEnableAccount",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RealDigitalEnableAccount__factory>;
    getContractFactory(
      name: "RealTokenizado",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RealTokenizado__factory>;
    getContractFactory(
      name: "STR",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.STR__factory>;
    getContractFactory(
      name: "SwapOneStep",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SwapOneStep__factory>;
    getContractFactory(
      name: "SwapTwoSteps",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SwapTwoSteps__factory>;

    getContractAt(
      name: "AccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "IAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "Pausable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "AddressDiscovery",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AddressDiscovery>;
    getContractAt(
      name: "CBDCAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CBDCAccessControl>;
    getContractAt(
      name: "KeyDictionary",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.KeyDictionary>;
    getContractAt(
      name: "RealDigital",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RealDigital>;
    getContractAt(
      name: "RealDigitalDefaultAccount",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RealDigitalDefaultAccount>;
    getContractAt(
      name: "RealDigitalEnableAccount",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RealDigitalEnableAccount>;
    getContractAt(
      name: "RealTokenizado",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RealTokenizado>;
    getContractAt(
      name: "STR",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.STR>;
    getContractAt(
      name: "SwapOneStep",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SwapOneStep>;
    getContractAt(
      name: "SwapTwoSteps",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SwapTwoSteps>;

    deployContract(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "AddressDiscovery",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AddressDiscovery>;
    deployContract(
      name: "CBDCAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CBDCAccessControl>;
    deployContract(
      name: "KeyDictionary",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.KeyDictionary>;
    deployContract(
      name: "RealDigital",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RealDigital>;
    deployContract(
      name: "RealDigitalDefaultAccount",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RealDigitalDefaultAccount>;
    deployContract(
      name: "RealDigitalEnableAccount",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RealDigitalEnableAccount>;
    deployContract(
      name: "RealTokenizado",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RealTokenizado>;
    deployContract(
      name: "STR",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.STR>;
    deployContract(
      name: "SwapOneStep",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SwapOneStep>;
    deployContract(
      name: "SwapTwoSteps",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SwapTwoSteps>;

    deployContract(
      name: "AccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "Pausable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "AddressDiscovery",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AddressDiscovery>;
    deployContract(
      name: "CBDCAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CBDCAccessControl>;
    deployContract(
      name: "KeyDictionary",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.KeyDictionary>;
    deployContract(
      name: "RealDigital",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RealDigital>;
    deployContract(
      name: "RealDigitalDefaultAccount",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RealDigitalDefaultAccount>;
    deployContract(
      name: "RealDigitalEnableAccount",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RealDigitalEnableAccount>;
    deployContract(
      name: "RealTokenizado",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RealTokenizado>;
    deployContract(
      name: "STR",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.STR>;
    deployContract(
      name: "SwapOneStep",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SwapOneStep>;
    deployContract(
      name: "SwapTwoSteps",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SwapTwoSteps>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
